package com.didichuxing.datachannel.agentmanager.common.enumeration.metrics;

import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * 指标字段
 * @author william
 */
public enum MetricFieldEnum {

    /*********************************** 系统相关 ***********************************/
    /*
     * 基础信息
     */
    SYSTEM_HOST_NAME(
            1,
            "host_name",
            "hostName",
            "主机名",
            MetricTypeEnum.SYSTEM_BASIC,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    SYSTEM_IP(
            2,
            "ip",
            "ips",
            "ip地址列表",
            MetricTypeEnum.SYSTEM_BASIC,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    SYSTEM_NTP_OFFSET(
            3,
            "system_ntp_offset",
            "systemNtpOffset",
            "源时钟与本地时钟的时间差（单位：秒）",
            MetricTypeEnum.SYSTEM_BASIC,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_SECOND,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),
    SYSTEM_STARTUP_TIME(
            4,
            "system_startup_time",
            "systemStartupTime",
            "系统启动时间",
            MetricTypeEnum.SYSTEM_BASIC,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.DATE_TIME,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    SYSTEM_UP_TIME(
            5,
            "system_up_time",
            "systemUptime",
            "系统运行时间",
            MetricTypeEnum.SYSTEM_BASIC,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_SECOND,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    /*
     * OS相关
     */
    SYSTEM_OS_TYPE(
            6,
            "os_type",
            "osType",
            "操作系统类型",
            MetricTypeEnum.SYSTEM_OS,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    SYSTEM_OS_VERSION(
            7,
            "os_version",
            "osVersion",
            "操作系统版本",
            MetricTypeEnum.SYSTEM_OS,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    SYSTEM_OS_KERNEL_VERSION(
            8,
            "os_kernel_version",
            "osKernelVersion",
            "操作系统内核版本",
            MetricTypeEnum.SYSTEM_OS,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    /*
     * Process相关
     */
    SYSTEM_PROCESS_BLOCKED(
            9,
            "system_process_blocked",
            "processesBlocked",
            "不可中断的睡眠状态下的进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_SLEEPING(
            10,
            "system_process_sleeping",
            "processesSleeping",
            "可中断的睡眠状态下的进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_ZOMBIES(
            11,
            "system_process_zombies",
            "processesZombies",
            "僵尸态进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_STOPPED(
            12,
            "system_process_stopped",
            "processesStopped",
            "暂停状态进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_RUNNING(
            13,
            "system_process_running",
            "processesRunning",
            "运行中的进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_IDLE(
            14,
            "system_process_idle",
            "processesIdle",
            "挂起的空闲进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_WAIT(
            15,
            "system_process_wait",
            "processesWait",
            "等待中的进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_DEAD(
            16,
            "system_process_dead",
            "processesDead",
            "回收中的进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_PAGING(
            17,
            "system_process_paging",
            "processesPaging",
            "分页进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_UNKNOWN(
            18,
            "system_process_unknown",
            "processesUnknown",
            "未知状态进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_TOTAL(
            19,
            "system_process_total",
            "processesTotal",
            "系统总进程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_PROCESS_TOTAL_THREADS(
            20,
            "system_process_total_threads",
            "processesTotalThreads",
            "系统总线程数",
            MetricTypeEnum.SYSTEM_PROCESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    /*
     * cpu 相关
     */
    SYSTEM_CPU_CORES(
            21,
            "system_cpu_cores",
            "cpuCores",
            "cpu核数",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.NONE,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),
    SYSTEM_CPU_UTIL(
            22,
            "system_cpu_util",
            "systemCpuUtil",
            "系统总体CPU使用率(单位：%)，使用率采用全核方式计数，如系统使用一颗核，则返回100，如使用两颗核，则返回200",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),
    SYSTEM_CPU_UTIL_TOTAL_PERCENT(
            23,
                    "system_cpu_util_total_percent",
                    "systemCpuUtilTotalPercent",
                    "系统总体CPU使用率（单位：%），使用总体百分比计数，如系统共2颗核，使用一颗核，则返回50%",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_SYSTEM(
            24,
            "system_cpu_system",
            "systemCpuSystem",
            "内核态CPU时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_CPU_USER(
            25,
            "system_cpu_user",
            "systemCpuUser",
            "用户态CPU时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_CPU_IDLE(
            26,
                    "system_cpu_idle",
                    "systemCpuIdle",
                    "cpu总体空闲率（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_SWITCHES(
            27,
                    "system_cpu_switches",
                    "systemCpuSwitches",
                    "每秒cpu上下文交换次数",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_USAGE_IRQ(
            28,
                    "system_cpu_usage_irq",
                    "systemCpuUsageIrq",
                    "CPU处理硬中断的时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_USAGE_SOFT_IRQ(
            29,
                    "system_cpu_usage_soft_irq",
                    "systemCpuUsageSoftIrq",
                    "CPU处理软中断的时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_LOAD_1(
            30,
            "system_cpu_load_1",
            "systemLoad1",
            "系统近1分钟平均负载",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_CPU_LOAD_5(
            31,
                    "system_cpu_load_5",
                    "systemLoad5",
                    "系统近5分钟平均负载",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_LOAD_15(
            32,
                    "system_cpu_load_15",
                    "systemLoad15",
                    "系统近15分钟平均负载",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_IO_WAIT(
            33,
                    "system_cpu_io_wait",
                    "systemCpuIOWait",
                    "系统等待I/O的CPU时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_GUEST(
            34,
                    "system_cpu_guest",
                    "systemCpuGuest",
                    "虚拟处理器CPU时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_CPU_STEAL(
            35,
                    "system_cpu_steal",
                    "systemCpuSteal",
                    "虚拟CPU的竞争等待时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    /*
     * memory 相关
     */
    SYSTEM_MEMORY_COMMIT_LIMIT(
            36,
                    "system_memory_commit_limit",
                    "systemMemCommitLimit",
                    "系统当前可分配的内存总量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_COMMITTED_AS(
            37,
                    "system_memory_committed_as",
                    "systemMemCommittedAs",
                    "系统已分配的包括进程未使用的内存量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_COMMITTED(
            38,
                    "system_memory_committed",
                    "systemMemCommitted",
                    "返回在磁盘分页文件上保留的物理内存量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_NON_PAGED(
            39,
            "system_memory_non_paged",
            "systemMemNonPaged",
            "不能写入磁盘的物理内存量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_MEMORY_PAGED(
            40,
                    "system_memory_paged",
                    "systemMemPaged",
                    "没被使用是可以写入磁盘的物理内存量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SHARED(
            41,
                    "system_memory_shared",
                    "systemMemShared",
                    "用作共享内存的物理RAM量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SLAB(
            42,
                    "system_memory_slab",
                    "systemMemSlab",
                    "内核用来缓存数据结构供自己使用的内存量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_TOTAL(
            43,
                    "system_memory_total",
                    "systemMemTotal",
                    "系统物理内存总量（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_FREE(
            44,
            "system_memory_free",
            "systemMemFree",
            "系统空闲内存大小（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),
    SYSTEM_MEMORY_USED(
            45,
                    "system_memory_used",
                    "systemMemUsed",
                    "系统已用内存大小（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_BUFFERED(
            46,
                    "system_memory_buffered",
                    "systemMemBuffered",
                    "块设备占用的缓存页，包括直接读写块设备、文件系统元数据、superblock（超级块中的数据其实就是文件卷的控制信息部分，也可以说它是卷资源表，有关文件卷的大部分信息都保存在这里。例如：硬盘分区中每个block的大小、硬盘分区上一共有多少个block group、以及每个block group中有多少个inode）所使用的缓存页（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_CACHED(
            47,
                    "system_memory_cached",
                    "systemMemCached",
                    "普通文件所占用的缓存页（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_FREE_PERCENT(
            48,
                    "system_memory_free_percent",
                    "systemMemFreePercent",
                    "系统内存空闲率（单位：%）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_USED_PERCENT(
            49,
                    "system_memory_used_percent",
                    "systemMemUsedPercent",
                    "系统内存使用率（单位：%）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SWAP_CACHED(
            50,
                    "system_memory_swap_cached",
                    "systemSwapCached",
                    "系统用作缓存的交换空间大小（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SWAP_FREE(
            51,
                    "system_memory_swap_free",
                    "systemSwapFree",
                    "系统空闲swap大小（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SWAP_FREE_PERCENT(
            52,
                    "system_memory_swap_free_percent",
                    "systemSwapFreePercent",
                    "系统空闲swap占比（单位：%）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SWAP_TOTAL(
            53,
                    "system_memory_swap_total",
                    "systemSwapTotal",
                    "系统swap总大小（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SWAP_USED(
            54,
                    "system_memory_swap_used",
                    "systemSwapUsed",
                    "系统已用swap大小（单位：MB）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_MEMORY_SWAP_USED_PERCENT(
            55,
                    "system_memory_swap_used_percent",
                    "systemSwapUsedPercent",
                    "系统已用swap占比（单位：%）",
            MetricTypeEnum.SYSTEM_MEMORY,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
                    null
    ),
    /*
     * disk 相关
     */
    SYSTEM_DISKS(
            56,
                    "system_disks",
                    "systemDisks",
                    "系统磁盘分区数",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
                    null
    ),
    SYSTEM_DISK_BYTES_TOTAL(
            57,
                    "system_disk_bytes_total",
                    "systemDiskBytesTotal",
                    "磁盘分区总容量（单位：MB）",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
                    null
    ),
    SYSTEM_DISK_BYTES_FREE(
            58,
            "system_disk_bytes_free",
            "systemDiskBytesFree",
            "磁盘分区余量大小（单位：MB）",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),
    SYSTEM_DISK_BYTES_USED(
            59,
                    "system_disk_bytes_used",
                    "systemDiskBytesUsed",
                    "磁盘分区用量大小（单位：MB）",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_USED_PERCENT(
            60,
                    "system_disk_used_percent",
                    "systemDiskUsedPercent",
                    "磁盘分区用量占比（单位：%）",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_INODES_TOTAL(
            61,
                    "system_disk_inodes_total",
                    "systemDiskInodesTotal",
                    "各磁盘分区inode总数量",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_INODES_FREE(
            62,
            "system_disk_inodes_free",
            "systemDiskInodesFree",
            "各磁盘分区空闲inode数量",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),
    SYSTEM_DISK_INODES_USED(
            63,
                    "system_disk_inodes_used",
                    "systemDiskInodesUsed",
                    "各磁盘分区已用inode数量",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_INODES_USED_PERCENT(
            64,
                    "system_disk_inodes_used_percent",
                    "systemDiskInodesUsedPercent",
                    "各磁盘分区已用inode占比（单位：%）",
            MetricTypeEnum.SYSTEM_DISK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    /*
     * disk io 相关
     */
    SYSTEM_DISK_IO_IO_AVG_QUSZ(
            65,
                    "io_avg_qusz",
                    "systemIOAvgQuSz",
                    "各设备平均IO队列长度",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_AVG_RQSZ(
            66,
                    "io_avg_rqsz",
                    "systemIOAvgRqSz",
                    "各设备平均IO请求大小（单位：扇区）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_AWAIT(
            67,
                    "io_await",
                    "systemIOAwait",
                    "各设备每次IO请求平均处理时间（单位：毫秒）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_R_AWAIT(
            68,
                    "io_r_await",
                    "systemIORAwait",
                    "各设备读请求平均耗时(单位：毫秒)",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_READ_REQUEST(
            69,
                    "io_read_request",
                    "systemIOReadRequest",
                    "各设备每秒读请求数量",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_READ_BYTES(
            70,
                    "io_read_bytes",
                    "systemIOReadBytes",
                    "各设备每秒读取字节数（单位：字节）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_RRQMS(
            71,
                    "io_read_rrqms",
                    "systemIORRQMS",
                    "各设备每秒合并到设备队列的读请求数",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_SVCTM(
            72,
                    "io_read_svctm",
                    "systemIOSVCTM",
                    "各设备每次IO平均服务时间（单位：毫秒）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_UTIL(
            73,
            "io_util",
            "systemIOUtil",
            "各设备I/O请求的时间百分比",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            true,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_W_AWAIT(
            74,
                    "io_w_await",
                    "systemIOWAwait",
                    "各设备写请求平均耗时（单位：毫秒）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_WRITE_REQUEST(
            75,
                    "io_write_request",
                    "systemIOWriteRequest",
                    "各设备每秒写请求数量",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_WRITE_BYTES(
            76,
                    "io_write_bytes",
                    "systemIOWriteBytes",
                    "各设备每秒写字节数（单位：字节）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_READ_WRITE_BYTES(
            77,
                    "io_read_write_bytes",
                    "systemIOReadWriteBytes",
                    "各设备每秒读、写字节数（单位：字节）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_IO_W_RQMS(
            78,
                    "io_w_rqms",
                    "systemIOWRQMS",
                    "各设备每秒合并到设备队列的写请求数",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_DISK_READ_TIME(
            79,
                    "disk_read_time",
                    "systemDiskReadTime",
                    "各设备读操作耗时（单位：毫秒）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_DISK_READ_TIME_PERCENT(
            80,
                    "disk_read_time_percent",
                    "systemDiskReadTimePercent",
                    "各设备读操作时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_DISK_WRITE_TIME(
            81,
                    "disk_write_time",
                    "systemDiskWriteTime",
                    "各设备写操作耗时（单位：毫秒）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_DISK_IO_DISK_WRITE_TIME_PERCENT(
            82,
                    "disk_write_time_percent",
                    "systemDiskWriteTimePercent",
                    "各设备写操作时间占比（单位：%）",
            MetricTypeEnum.SYSTEM_DISK_IO,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    /*
     * fd 相关
     */
    SYSTEM_FD_FILES_MAX(
            83,
                    "fd_files_max",
                    "systemFilesMax",
                    "系统可以打开的最大文件句柄数",
            MetricTypeEnum.SYSTEM_FILE_HANDLES,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_FD_FILES_ALLOCATED(
            84,
                    "fd_files_allocated",
                    "systemFilesAllocated",
                    "系统已分配文件句柄数",
            MetricTypeEnum.SYSTEM_FILE_HANDLES,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_FD_FILES_LEFT(
            85,
                    "fd_files_left",
                    "systemFilesLeft",
                    "系统未分配文件句柄数",
            MetricTypeEnum.SYSTEM_FILE_HANDLES,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_FD_FILES_USED_PERCENT(
            86,
                    "fd_files_used_percent",
                    "systemFilesUsedPercent",
                    "系统使用文件句柄占已分配百分比（单位：%）",
            MetricTypeEnum.SYSTEM_FILE_HANDLES,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_FD_FILES_USED(
            87,
                    "fd_files_used",
                    "systemFilesUsed",
                    "系统使用的已分配文件句柄数",
            MetricTypeEnum.SYSTEM_FILE_HANDLES,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_FD_FILES_NOT_USED(
            88,
                    "fd_files_not_used",
                    "systemFilesNotUsed",
                    "系统未使用的已分配文件句柄数",
            MetricTypeEnum.SYSTEM_FILE_HANDLES,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    /*
     * net card 相关
     */
    SYSTEM_NET_CARDS(
            89,
                    "net_cards",
                    "systemNetCards",
                    "网卡数",
            MetricTypeEnum.SYSTEM_NET_CARD,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_CARD_BAND_WIDTH(
            90,
                    "net_card_band_width",
                    "systemNetCardsBandWidth",
                    "各网卡最大带宽（单位：MB）",
            MetricTypeEnum.SYSTEM_NET_CARD,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_CARD_RECEIVE_BYTES_PS(
            91,
                    "net_card_receive_bytes_ps",
                    "systemNetCardsReceiveBytesPs",
                    "各网卡设备每秒下行流量（单位：字节）",
            MetricTypeEnum.SYSTEM_NET_CARD,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_CARD_SEND_BYTES_PS(
            92,
                    "net_card_send_bytes_ps",
                    "systemNetCardsSendBytesPs",
                    "各网卡设备每秒上行流量（单位：字节）",
            MetricTypeEnum.SYSTEM_NET_CARD,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            true,
            SortTypeEnum.DESC
            ),
    /*
     * net work 相关
     */
    SYSTEM_NET_WORK_RECEIVE_BYTES_PS(
            93,
                    "system_network_receive_bytes_ps",
                    "systemNetworkReceiveBytesPs",
                    "系统网络每秒下行流量（单位：字节）",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),
    SYSTEM_NET_WORK_SEND_BYTES_PS(
            94,
                    "system_network_send_bytes_ps",
                    "systemNetworkSendBytesPs",
                    "系统网络每秒上行流量（单位：字节）",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_CONNECTION_NUM(
            95,
                    "system_network_tcp_connection_num",
                    "systemNetworkTcpConnectionNum",
                    "系统tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_LISTENING_NUM(
            96,
                    "system_network_tcp_listening_num",
                    "systemNetworkTcpListeningNum",
                    "系统处于Listening状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_ESTABLISHED_NUM(
            97,
                    "system_network_tcp_established_num",
                    "systemNetworkTcpEstablishedNum",
                    "系统处于ESTABLISHED状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_SYN_SENT_NUM(
            98,
                    "system_network_tcp_syn_sent_num",
                    "systemNetworkTcpSynSentNum",
                    "系统处于SYN_SENT状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_SYN_RECV_NUM(
            99,
                    "system_network_tcp_syn_recv_num",
                    "systemNetworkTcpSynRecvNum",
                    "系统处于SYN_RECV状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_FIN_WAIT_1_NUM(
            100,
                    "system_network_tcp_fin_wait_1_num",
                    "systemNetworkTcpFinWait1Num",
                    "系统处于FIN_WAIT1状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_FIN_WAIT_2_NUM(
            101,
                    "system_network_tcp_fin_wait_2_num",
                    "systemNetworkTcpFinWait2Num",
                    "系统处于FIN_WAIT2状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_TIME_WAIT_NUM(
            102,
                    "system_network_tcp_time_wait_num",
                    "systemNetworkTcpTimeWaitNum",
                    "系统处于TIME_WAIT状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_CLOSED_NUM(
            103,
                    "system_network_tcp_closed_num",
                    "systemNetworkTcpClosedNum",
                    "系统处于CLOSED状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_CLOSE_WAIT_NUM(
            104,
                    "system_network_tcp_close_wait_num",
                    "systemNetworkTcpCloseWaitNum",
                    "系统处于CLOSE_WAIT状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_CLOSING_NUM(
            105,
                    "system_network_tcp_closing_num",
                    "systemNetworkTcpClosingNum",
                    "系统处于CLOSING状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_LAST_ACK_NUM(
            106,
                    "system_network_tcp_last_ack_num",
                    "systemNetworkTcpLastAckNum",
                    "系统处于LAST_ACK状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_NONE_NUM(
            107,
                    "system_network_tcp_none_num",
                    "systemNetworkTcpNoneNum",
                    "系统处于未知状态的tcp连接数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_ACTIVE_OPENS(
            108,
                    "system_network_tcp_active_opens",
                    "systemNetworkTcpActiveOpens",
                    "采样周期内tcp主动连接次数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_PASSIVE_OPENS(
            109,
                    "system_network_tcp_passive_opens",
                    "systemNetworkTcpPassiveOpens",
                    "采样周期内tcp被动连接次数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_ATTEMPT_FAILS(
            110,
                    "system_network_tcp_attempt_fails",
                    "systemNetworkTcpAttemptFails",
                    "采样周期内tcp连接失败次数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_ESTAB_RESETS(
            111,
                    "system_network_tcp_estab_resets",
                    "systemNetworkTcpEstabResets",
                    "采样周期内tcp连接异常断开次数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_RETRANS_SEGS(
            112,
                    "system_network_tcp_retrans_segs",
                    "systemNetworkTcpRetransSegs",
                    "采样周期内tcp重传的报文段总个数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_TCP_EXT_LISTEN_OVER_FLOWS(
            113,
                    "system_network_tcp_ext_listen_over_flows",
                    "systemNetworkTcpExtListenOverflows",
                    "采样周期内tcp监听队列溢出次数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_UDP_IN_DATAGRAMS(
            114,
                    "system_network_udp_in_datagrams",
                    "systemNetworkUdpInDatagrams",
                    "采样周期内udp入包量",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_UDP_OUT_DATAGRAMS(
            115,
                    "system_network_udp_out_datagrams",
                    "systemNetworkUdpOutDatagrams",
                    "采样周期内udp出包量",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_UDP_IN_ERRORS(
            116,
                    "system_network_udp_in_errors",
                    "systemNetworkUdpInErrors",
                    "采样周期内udp入包错误数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_UDP_NO_PORTS(
            117,
                    "system_network_udp_no_ports",
                    "systemNetworkUdpNoPorts",
                    "采样周期内udp端口不可达个数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_UDP_SEND_BUFFER_ERRORS(
            118,
                    "system_network_udp_send_buffer_errors",
                    "systemNetworkUdpSendBufferErrors",
                    "采样周期内udp发送缓冲区满次数",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_NET_CARDS_BAND_WIDTH(
            119,
                    "system_network_net_cards_band_width",
                    "systemNetCardsBandWidth",
                    "系统网卡总带宽（单位：字节）",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    SYSTEM_NET_WORK_SEND_AND_RECEIVE_BYTES_PS(
            120,
            "system_network_send_and_receive_bytes_ps",
            "systemNetworkSendAndReceiveBytesPs",
            "系统网络每秒总流量（单位：字节）",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),
    SYSTEM_NET_WORK_BAND_WIDTH_USED_PERCENT(
            121,
                    "system_net_work_band_width_used_percent",
                    "systemNetWorkBandWidthUsedPercent",
                    "系统网络带宽使用率（单位：%)",
            MetricTypeEnum.SYSTEM_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),
    /*********************************** 进程相关 ***********************************/
    /*
     * 基础信息
     */
    PROCESS_START_UP_TIME(
            122,
            "process_startup_time",
            "procStartupTime",
            "进程启动时间",
            MetricTypeEnum.PROCESS_BASIC,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.DATE_TIME,
            MetricDisplayTypeEnum.LABLE,
            false,
            SortTypeEnum.DESC
    ),
    PROCESS_UP_TIME(
            123,
                    "process_up_time",
                    "procUptime",
                    "进程运行时间（单位：秒）",
            MetricTypeEnum.PROCESS_BASIC,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_SECOND,
            MetricDisplayTypeEnum.LABLE,
            false,
            SortTypeEnum.DESC
            ),
    PROCESS_PID(
            124,
                    "process_pid",
                    "procPid",
                    "进程 pid",
            MetricTypeEnum.PROCESS_BASIC,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            SortTypeEnum.DESC
            ),
    /*
     * cpu 相关
     */
    PROCESS_CPU_UTIL(
            125,
            "process_cpu_util",
            "procCpuUtil",
            "进程cpu使用率(单位：%) 使用率采用全核方式计数，如进程使用一颗核，则返回100，如进程使用两颗核，则返回200",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            SortTypeEnum.DESC
    ),
    PROCESS_CPU_UTIL_TOTAL_PERCENT(
            126,
                    "process_cpu_util_total_percent",
                    "procCpuUtilTotalPercent",
                    "进程cpu使用率(单位：%) 使用率为总使用比率，如进程使用一颗核，系统共10核，则返回0.1 = 10%",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),
    PROCESS_CPU_SYS(
            127,
                    "process_cpu_sys",
                    "procCpuSys",
                    "进程内核态cpu使用率（单位：%）",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    PROCESS_CPU_USER(
            128,
                    "process_cpu_user",
                    "procCpuUser",
                    "进程用户态cpu使用率（单位：%）",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.PERCENT,
            MetricUnitEnum.PERCENT,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    PROCESS_CPU_SWITCHES_PS(
            129,
                    "process_cpu_switches_ps",
                    "procCpuSwitchesPS",
                    "进程cpu每秒上下文交换次数",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    PROCESS_CPU_VOLUNTARY_SWITCHES_PS(
            130,
                    "process_cpu_voluntary_switches_ps",
                    "procCpuVoluntarySwitchesPS",
                    "当前进程cpu每秒自愿上下文交换次数（自愿上下文切换，是指进程无法获取所需资源，导致的上下文切换。比如说， I/O、内存等系统资源不足时，就会发生自愿上下文切换 pidstat）",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    PROCESS_CPU_NON_VOLUNTARY_SWITCHES_PS(
            131,
                    "process_cpu_non_voluntary_switches_ps",
                    "procCpuNonVoluntarySwitchesPS",
                    "当前进程cpu每秒非自愿上下文交换次数（非自愿上下文切换，则是指进程由于时间片已到等原因，被系统强制调度，进而发生的上下文切换。比如说，大量进程都在争抢 CPU 时，就容易发生非自愿上下文切换 pidstat）",
            MetricTypeEnum.PROCESS_CPU,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),
    /*
     * memory 相关
     */
    PROCESS_MEMORY_USED(
            132,
                    "process_memory_used",
                    "procMemUsed",
                    "当前进程内存使用量（单位：MB）",
            MetricTypeEnum.PROCESS_MEMORY,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            SortTypeEnum.DESC
            ),

    //TODO：


























    PROCESS_NET_WORK_SEND_BYTES_PS(
            14,
            "process_network_send_bytes_ps",
            "procNetworkSendBytesPs",
            "当前进程网络每秒上行流量",
            MetricTypeEnum.PROCESS_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),

    PROCESS_NET_WORK_RECEIVE_BYTES_PS(
            15,
            "process_network_receive_bytes_ps",
            "procNetworkReceiveBytesPs",
            "当前进程网络每秒下行流量",
            MetricTypeEnum.PROCESS_NET_WORK,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),

    JVM_FULL_GC_COUNT(
            16,
            "process_jvm_full_gc_count",
            "jvmProcFullGcCount",
            "采样周期内 full gc 次数",
            MetricTypeEnum.PROCESS_GC,
            AggregationCalcFunctionEnum.SUM,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            false,
            null
    ),

    PROCESS_FD_USED(
            17,
            "process_open_fd_count",
            "procOpenFdCount",
            "当前进程打开fd数量",
            MetricTypeEnum.PROCESS_FD,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),

    /*********************************** agent 相关 ***********************************/

    AGENT_VERSION(
            18,
            "agent_version",
            "agentVersion",
            "agent版本号",
            MetricTypeEnum.AGENT_BUSINESS,
            null,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.LABLE,
            false,
            null
    ),

    AGENT_WRITE_COUNT(
            19,
            "write_count",
            "writeCount",
            "采样周期内出口采集条数 单位：条",
            MetricTypeEnum.AGENT_BUSINESS,
            AggregationCalcFunctionEnum.SUM,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),

    AGENT_WRITE_BYTES(
            20,
                    "write_bytes",
                    "writeBytes",
                    "采样周期内出口采集流量 单位：bytes",
            MetricTypeEnum.AGENT_BUSINESS,
            AggregationCalcFunctionEnum.SUM,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),

    AGENT_RUNNING_COLLECT_TASK_COUNT(
            21,
            "running_collect_task_num",
            "runningCollectTaskNum",
            "运行状态采集任务数",
            MetricTypeEnum.AGENT_BUSINESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),

    AGENT_RUNNING_COLLECT_PATH_COUNT(
            22,
            "running_collect_path_num",
            "runningCollectPathNum",
            "运行状态采集路径数",
            MetricTypeEnum.AGENT_BUSINESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.NONE,
            MetricUnitEnum.NONE,
            MetricDisplayTypeEnum.SINGLE_LINE_CHAT,
            true,
            null
    ),

    /*********************************** 采集任务相关 ***********************************/

    LOG_COLLECT_TASK_BUSINESS_TIMESTAMP(
            23,
            "business_time",
            "businessTimestamp",
            "采集业务时间",
            MetricTypeEnum.LOG_COLLECT_TASK_BUSINESS,
            AggregationCalcFunctionEnum.MIN,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.DATE_TIME,
            MetricDisplayTypeEnum.LABLE,
            true,
            SortTypeEnum.DESC
    ),

    LOG_COLLECT_TASK_SEND_BYTES(
            24,
     "send_bytes",
     "sendBytes",
     "日志发送字节数",
            MetricTypeEnum.LOG_COLLECT_TASK_BUSINESS,
            AggregationCalcFunctionEnum.SUM,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            true,
            SortTypeEnum.DESC
    ),

    LOG_COLLECT_TASK_SEND_COUNT(
            25,
            "send_count",
            "sendCount",
            "采样周期内日志发送条数",
            MetricTypeEnum.LOG_COLLECT_TASK_BUSINESS,
            AggregationCalcFunctionEnum.SUM,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.BYTE,
            MetricUnitEnum.M_BYTE,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            true,
            SortTypeEnum.DESC
    ),

    LOG_COLLECT_TASK_READ_TIME_PER_EVENT(
            26,
            "read_time_per_event",
            "readTimePerEvent",
            "采样周期内单 log event 读取耗时 (单位：纳秒)",
            MetricTypeEnum.LOG_COLLECT_TASK_BUSINESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.STATISTICS,
            MetricUnitEnum.TIMESTAMP_NANOSECOND,
            MetricUnitEnum.TIMESTAMP_NANOSECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),

    LOG_COLLECT_TASK_MAX_BUSINESS_TIMESTAMP_DELAY(
            27,
            "max_business_timestamp_delay",
            "maxBusinessTimestampDelay",
            "数据业务时间最大延迟 （单位：秒）",
            MetricTypeEnum.LOG_COLLECT_TASK_BUSINESS,
            AggregationCalcFunctionEnum.MAX,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_SECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    ),

    LOG_COLLECT_TASK_LIMIT_TIME(
            28,
            "limit_time",
            "limitTime",
            "采样周期内限流时长（单位：秒）",
            MetricTypeEnum.LOG_COLLECT_TASK_BUSINESS,
            AggregationCalcFunctionEnum.SUM,
            MetricValueTypeEnum.CURRENT,
            MetricUnitEnum.TIMESTAMP_MILLISECOND,
            MetricUnitEnum.TIMESTAMP_SECOND,
            MetricDisplayTypeEnum.MULTI_LINE_CHAT,
            false,
            SortTypeEnum.DESC
    )

    ;

    /**
     * 指标代码
     */
    private Integer code;

    /**
     * 指标名
     */
    private String metricName;

    /**
     * 存储系统字段名
     */
    private String fieldName;

    /**
     * 指标描述
     */
    private String description;

    /**
     * 指标类型（对应MetricTypeEnum.code）
     */
    private MetricTypeEnum metricType;

    /**
     * 该指标计算时采用的聚合函数枚举
     */
    private AggregationCalcFunctionEnum aggregationCalcFunction;

    /**
     * 指标值类型枚举
     */
    private MetricValueTypeEnum metricValueType;

    /**
     * 基础单位
     */
    private MetricUnitEnum baseUnit;

    /**
     * 显示单位
     */
    private MetricUnitEnum displayUnit;

    /**
     * 指标展示类型
     */
    private MetricDisplayTypeEnum metricDisplayType;

    /**
     * 是否默认选中
     */
    private boolean checked;

    private SortTypeEnum sortTypeEnum;

    MetricFieldEnum(
            Integer code,
            String metricName,
            String fieldName,
            String description,
            MetricTypeEnum metricType,
            AggregationCalcFunctionEnum aggregationCalcFunction,
            MetricValueTypeEnum metricValueType,
            MetricUnitEnum baseUnit,
            MetricUnitEnum displayUnit,
            MetricDisplayTypeEnum metricDisplayType,
            boolean checked,
            SortTypeEnum sortTypeEnum
            ) {
        this.code = code;
        this.metricName = metricName;
        this.fieldName = fieldName;
        this.description = description;
        this.metricType = metricType;
        this.aggregationCalcFunction = aggregationCalcFunction;
        this.metricValueType = metricValueType;
        this.baseUnit = baseUnit;
        this.displayUnit = displayUnit;
        this.metricDisplayType = metricDisplayType;
        this.checked = checked;
        this.sortTypeEnum = sortTypeEnum;
    }

    public String getMetricName() {
        return metricName;
    }

    public String getFieldName() {
        return fieldName;
    }

    public String getDescription() {
        return description;
    }

    public MetricTypeEnum getMetricType() {
        return metricType;
    }

    public AggregationCalcFunctionEnum getAggregationCalcFunction() {
        return aggregationCalcFunction;
    }

    public MetricValueTypeEnum getMetricValueType() {
        return metricValueType;
    }

    public MetricUnitEnum getBaseUnit() {
        return baseUnit;
    }

    public MetricUnitEnum getDisplayUnit() {
        return displayUnit;
    }

    public MetricDisplayTypeEnum getMetricDisplayType() {
        return metricDisplayType;
    }

    public Integer getCode() {
        return code;
    }

    public boolean isChecked() {
        return checked;
    }

    public SortTypeEnum getSortTypeEnum() {
        return sortTypeEnum;
    }

    /**
     * 根据指标代码返回对应指标枚举定义
     * @param metricCode 指标名
     * @return 如指标代码在指标枚举集存在，返回指标名对应指标枚举定义，如不存在，返回 null
     */
    public static MetricFieldEnum fromMetricCode(Integer metricCode) {
        for (MetricFieldEnum value : MetricFieldEnum.values()) {
            if (value.code.equals(metricCode)) {
                return value;
            }
        }
        return null;
    }

    /**
     * 根据给定指标类型获取属该指标类型的指标集
     * @param metricTypeEnum 指标类型
     * @return 返回根据给定指标类型获取属该指标类型的指标集
     */
    public static List<MetricFieldEnum> fromMetricTypeEnum(MetricTypeEnum metricTypeEnum) {
        List<MetricFieldEnum> result = new ArrayList<>();
        for (MetricFieldEnum value : MetricFieldEnum.values()) {
            if (value.metricType.equals(metricTypeEnum)) {
                result.add(value);
            }
        }
        return result;
    }

}
