export default {

  // common actions' constants
  SET_LOADING: 'SET_LOADING',

  //
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  SET_NAME: 'SET_NAME',

  SET_MODAL_ID: 'SET_MODAL_ID',
  SET_DRAWER_ID: 'SET_DRAWER_ID',

  SET_TIME_RANGE: 'SET_TIME_RANGE',

  SET_COLLECT_TYPE: 'SET_COLLECT_TYPE',
  SET_LOG_TYPE: 'SET_LOG_TYPE',

  SET_CONTENT: 'SET_CONTENT',

  SET_REFRESH_LOADING: 'SET_REFRESH_LOADING',

  SET_CHART_METRICS: 'SET_CHART_METRICS',

  //权限点action
  SET_PERMISSION_POINTS: 'SET_PERMISSION_POINTS',
  SET_RES_PERMISSIONS:'SET_RES_PERMISSIONS',
  //租户和项目action
  SET_TENANT_PROJECT: 'SET_TENANT_PROJECT',
  SET_COLLECTSTATE: 'SET_COLLECTSTATE',
  SET_COLLECTTASK_DETAIL: 'SET_COLLECTTASK_DETAIL',
};