import { byteToMB } from '../utils';
import { Utils } from '@didi/dcloud-design';

export const cardList = [
  {
    title: '主机数',
    code: 4,
    api: 'hostNum',
    icon: 'icon-zhujizongshu',
    text: '容器数',
    textCode: 5,
    textApi: 'containerNum',
  },
  {
    title: 'agent数',
    code: 6,
    api: 'agentNum',
    icon: 'icon-Agentzongshu',
    text: '空转agent数',
    textCode: 1,
    textApi: 'nonRelateAnyLogCollectTaskAgentNum',
  },
  {
    title: '服务数',
    code: '',
    api: 'serviceNum',
    icon: 'icon-fuwushu',
    text: '未关联主机服务数',
    textCode: 1,
    textApi: 'nonRelateAnyHostServiceNum',
  },
  {
    title: '采集任务数',
    code: 0,
    api: 'logCollectTaskNum',
    icon: 'icon-caijirenwuzongshu',
    text: '僵尸采集任务数',
    textCode: 7,
    textApi: 'nonRelateAnyHostLogCollectTaskNum',
  },
  {
    title: '采集路径数',
    code: 2,
    api: 'logCollectPathNum',
    icon: 'icon-caijilujingzongshu',
  },
  {
    title: '全部agent cpu耗费',
    code: '',
    api: 'agentCpuCoresSpend',
    icon: 'icon-a-cpuhaofei',
    unit: 'core',
  },
  {
    title: '全部agent 内存耗费',
    code: '',
    api: 'agentMemorySpend',
    icon: 'icon-neicunhaofei',
    // unit: 'GB',
    type: 'formatSize',
    format: Utils.formatSize,
  },
  {
    title: '全部agent实时上行流量',
    code: '',
    api: 'agentUplinkBytes',
    icon: 'icon-shanghangliuliang',
    // unit: 'M',
    tip: 'byte',
    format: Utils.formatSize,
    type: 'formatSize',
    text: '全部agent实时下行流量',
    textCode: '',
    textApi: 'agentDownLinkBytes',
  },
  {
    title: '全部agent当日采集量',
    code: 10,
    api: 'agentSendBytesDay',
    icon: 'icon-dangricaijiliang',
    tip: 'byte',
    type: 'formatSize',
    format: Utils.formatSize,
  },
  {
    title: '全部agent当日采集条数',
    code: 11,
    api: 'agentSendLogEventsDay',
    icon: 'icon-dangricaijitiaoshu',
    unit: '条',
    tip: '条',
    // format: countChange,
  },
  {
    title: '近1分钟agent采集量',
    code: '',
    api: 'agentSendBytesLast1Minute',
    icon: 'icon-dangricaijiliang',
    tip: 'byte',
    format: Utils.formatSize,
  },
  {
    title: '近1分钟agent采集条数',
    code: '',
    api: 'agentSendLogEventsLast1Minute',
    icon: 'icon-dangricaijitiaoshu',
    unit: '条',
    tip: '条',
  },
];
